name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
    - uses: haskell-actions/setup@6037f33647c3f17758a2356c80fc4a53d7e0685d # v2
      with:
        ghc-version: '9.4.7'
    - uses: tox-dev/action-pre-commit-uv@e09b8958484dfe71f4ac3bc7afb230ba506402ec # v1.0.5
