name: Publish to Hackage

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: hackage
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: haskell-actions/setup@0f8e8c99d88aeb3fbfd523f1ef2c6f762d10d64d # v2
      - name: cabal sdist
        run: cabal sdist
      - name: cabal upload
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
        run: cabal upload --publish --token="$HACKAGE_API_KEY" dist-newstyle/sdist/*.tar.gz
